import dayjs from 'dayjs'

export const data = [
  {
    type: 1,
    title: 'Task 1',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 1,
    title: 'Task 2',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 1,
    title: 'Task 3',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 1,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 2,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 2,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 2,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'Task 4',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
]
