import dayjs from 'dayjs'

export const dataTest = [
  {
    type: 1,
    title: 'a',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-08-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 1,
    title: 'c',
    timeStart: dayjs('2019-03-25').valueOf(),
    timeEnd: dayjs('2019-06-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 1,
    title: 'b',
    timeStart: dayjs('2019-02-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 1,
    title: 'Task 4',
    timeStart: dayjs('2019-07-25').valueOf(),
    timeEnd: dayjs('2019-04-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 2,
    title: 'rt',
    timeStart: dayjs('2019-06-25').valueOf(),
    timeEnd: dayjs('2019-04-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 2,
    title: 'egr',
    timeStart: dayjs('2019-11-25').valueOf(),
    timeEnd: dayjs('2019-09-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 2,
    title: 'rff',
    timeStart: dayjs('2019-2-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'Task 4',
    timeStart: dayjs('2019-8-25').valueOf(),
    timeEnd: dayjs('2019-10-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'Task 4',
    timeStart: dayjs('2019-4-25').valueOf(),
    timeEnd: dayjs('2019-07-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'ryg',
    timeStart: dayjs('2019-5-25').valueOf(),
    timeEnd: dayjs('2019-04-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 3,
    title: 'lkfhdf',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-01-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'jgjf',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-09-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'utydg',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-08-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'sdfdg',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-02-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
  {
    type: 4,
    title: 'tsd',
    timeStart: dayjs('2019-01-25').valueOf(),
    timeEnd: dayjs('2019-06-28').valueOf(),
    description: 'Lorem ipsum dolor sit amet, conse',
    status: 'new',
  },
]
