export const FETCH_USER_INFOMTAION_ACTION = 'FETCH_USER_INFOMTAION_ACTION';
export const FETCH_USER_INFOMTAION_SUCCESS_ACTION = 'FETCH_USER_INFOMTAION_SUCCESS_ACTION';
export const FETCH_USER_INFOMTAION_FAILD_ACTION = 'FETCH_USER_INFOMTAION_FAILD_ACTION';

export const UPDATE_USER_PROFILE_ACTION = 'UPDATE_USER_PROFILE_ACTION';
export const UPDATE_USER_PROFILE_SUCCESS_ACTION = 'UPDATE_USER_PROFILE_SUCCESS_ACTION';
export const UPDATE_USER_PROFILE_FAILD_ACTION = 'UPDATE_USER_PROFILE_FAILD_ACTION';

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const SEND_FORGOT_PASSWORD_CODE = 'SEND_FORGOT_PASSWORD_CODE'
export const SUBMIT_FORGOT_PASSWORD = 'SUBMIT_FORGOT_PASSWORD'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'